NUM_DEVICES: 4

# Define names of devices
DEVICES_TYPES:
- 'cryo'
- 'mks925_1'
- 'mks925_2'
- 'mks972_1'

# Define whether device is on MUX'd serial port or not
IS_MUXED:
- no
- yes
- yes
- yes

# Define IDN Commands
IDN_CMD:
- 'I'
- '@254SN?;FF'
- '@254SN?;FF'
- '@254SN?;FF'

# Define READ Commands
READ_CMD:
- 'Q'
- '@254PR4?;FF'
- '@254PR4?;FF'
- '@254PR4?;FF'

# Define IDN responses
IDN_ACK:
- 'Cryo Diode'
- '925A0232'
- '925A0233'
- '972AO903'

# Define ERR Responses
ERR_NAK:
- 'Error?'
- 'NAK'
- 'NAK'
- 'NAK'


# Define Error codes
ERR_CODES:
- 'Cryo Reading Error'

- '8': 'Zero adjustment at too high pressure'
  '9': 'Atmospheric adjustment at too low pressure'
  '160': 'Unrecognized message'
  '169': 'Invalid argument'
  '172': 'Value out of range'
  '175': 'Command/query character invalid'
  '180': 'Not in setup mode (locked)'

- '8': 'Zero adjustment at too high pressure'
  '9': 'Atmospheric adjustment at too low pressure'
  '160': 'Unrecognized message'
  '169': 'Invalid argument'
  '172': 'Value out of range'
  '175': 'Command/query character invalid'
  '180': 'Not in setup mode (locked)'

- '8': 'Zero adjustment at too high pressure'
  '9': 'Atmospheric adjustment at too low pressure'
  '160': 'Unrecognized message'
  '169': 'Invalid argument'
  '172': 'Value out of range'
  '175': 'Command/query character invalid'
  '180': 'Not in setup mode (locked)'